# -*- coding: utf-8 -*-
"""Proyek Analisis Data_Diwa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ns_dTF_xqplF_A1CmpKpr94VZ4YZpg5I

# Proyek Analisis Data: [Bike Sharing Dataset]
- **Nama:** Diwa
- **Email:** cdaspro5@gmail.com
- **ID Dicoding:** [diwa_prasetyo_ekSz]

## Menentukan Pertanyaan Bisnis

- Analisis korelasi cuaca dan rental sepeda
- Analisis rental sepeda musiman

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""## Data Wrangling

### Gathering Data
"""

url ='https://raw.githubusercontent.com/DiwaPrasetyo02/submission-data-analysis/main/day.csv'
df = pd.read_csv(url)
df

"""### Assessing Data"""

df.isnull().sum()

df.duplicated().sum()

"""### Cleaning Data"""

#Tidak Perlu di lakukan cleaning karena data sudah aman

"""## Exploratory Data Analysis (EDA)

### Explore ...
"""

df.describe(include="all")

df.hist()

"""## Visualization & Explanatory Analysis"""

# Plot bar chart
plt.figure(figsize=(10, 6))
sns.barplot(x='season', y='cnt', data=df, estimator=sum, color="red")
plt.title('Total Count per Season')
plt.xlabel('Season')
plt.ylabel('Total Count')
plt.show()

# Plot bar chart
plt.figure(figsize=(10, 6))
sns.barplot(x='weathersit', y='cnt', data=df, estimator=sum, color="green")
plt.title('Total Count per weathersit')
plt.xlabel('weathersit')
plt.ylabel('Total Count')
plt.show()

"""### Pertanyaan 1:"""

# Apa hasil dari analisis hubungan kolom cnt dan kolom musim?

"""### Pertanyaan 2:"""

# Apa hasil dari analisis hubungan kolom cnt dan kolom cuaca?

"""## Conclusion

- Hasil dari analisis menjawab bahwa penjualan naik pada musim gugur
- Hasil dari analisis menjawab bahwa penjualan naik pada cuaca yang cerah dan sedikit berawan
"""